export type MediaType = "image" | "video";

export type GalleryItem = {
  id: string;
  src: string;
  no: string;
  title: string;
  meta: string;
  type?: MediaType;
  poster?: string;
  width?: number;
  height?: number;
  col: number;
  row: number;
  align?: "left" | "right";
  mobileCol?: number;
  mobileRow?: number;
  overlayColor?: string;
};

const VIDEO_EXTENSIONS = /\.(mp4|webm|mov|m4v|ogg)$/i;

export function getMediaType(item: GalleryItem): MediaType {
  if (item.type) return item.type;
  return VIDEO_EXTENSIONS.test(item.src) ? "video" : "image";
}

export const galleryItems: GalleryItem[] = [
  {
    id: "01",
    src: "/gallery/01_MOAD_Tahr_01.webp",
    width: 1920,
    height: 1920,
    no: "01",
    title: "Haditehrani, Office",
    meta: "Pune, 2023",
    col: 4,
    row: 2,
    mobileCol: 2,
    mobileRow: 2,
    overlayColor: "rgb(69, 73, 65)",
  },
  {
    id: "02",
    src: "/gallery/01_MOAD_Tahr_02.webp",
    width: 1920,
    height: 823,
    no: "02",
    title: "Courtyard House",
    meta: "Pune, 2022",
    col: 2,
    row: 1,
    mobileCol: 1,
    mobileRow: 1,
    overlayColor: "rgb(50, 52, 66)",
  },
  {
    id: "03",
    src: "/gallery/01_MOAD_Tahr_03.webp",
    width: 1920,
    height: 1920,
    no: "03",
    title: "Garden Residence",
    meta: "Pune, 2022",
    col: 2,
    row: 1,
    mobileCol: 1,
    mobileRow: 1,
    overlayColor: "rgb(69, 69, 69)",
  },
  {
    id: "04",
    src: "/gallery/01_MOAD_Tahr_04.webp",
    width: 1920,
    height: 1920,
    no: "04",
    title: "Coastal Pavilion",
    meta: "Åland, 2021",
    col: 6,
    row: 1,
    mobileCol: 2,
    mobileRow: 1,
    overlayColor: "rgb(71, 60, 56)",
  },
  {
    id: "05",
    src: "/gallery/02_CabinStudy_01.webp",
    width: 1920,
    height: 1920,
    no: "05",
    title: "Forest Retreat",
    meta: "Sarek, 2023",
    col: 3,
    row: 1,
    mobileCol: 1,
    mobileRow: 2,
    overlayColor: "rgb(50, 60, 48)",
  },
  {
    id: "06",
    src: "/gallery/02_CabinStudy_02.webp",
    width: 1920,
    height: 1920,
    no: "06",
    title: "Stone House",
    meta: "Öland, 2020",
    col: 3,
    row: 1,
    mobileCol: 1,
    mobileRow: 1,
    overlayColor: "rgb(64, 78, 90)",
  },
  {
    id: "07",
    src: "/gallery/02_CabinStudy_03.webp",
    width: 1920,
    height: 1920,
    no: "07",
    title: "Timber Pavilion",
    meta: "Öland, 2020",
    col: 3,
    row: 1,
    mobileCol: 1,
    mobileRow: 1,
    overlayColor: "rgb(55, 62, 63)",
  },
  {
    id: "08",
    src: "/gallery/02_CabinStudy_04.webp",
    width: 1920,
    height: 1920,
    no: "08",
    title: "Pine Facade",
    meta: "Halland, 2019",
    col: 3,
    row: 1,
    mobileCol: 1,
    mobileRow: 2,
    overlayColor: "rgb(63, 68, 65)",
  },
  {
    id: "09",
    src: "/gallery/03_Concordia_Admiralty_Estates_01.webp",
    width: 1920,
    height: 1920,
    no: "09",
    title: "Reflection House",
    meta: "Malmö, 2024",
    col: 6,
    row: 2,
    mobileCol: 2,
    mobileRow: 2,
    overlayColor: "rgb(76, 77, 81)",
  },
  {
    id: "10",
    src: "/gallery/03_Concordia_Admiralty_Estates_02.webp",
    width: 1920,
    height: 1920,
    no: "10",
    title: "Brick Residence",
    meta: "Skåne, 2023",
    col: 3,
    row: 1,
    mobileCol: 1,
    mobileRow: 1,
    overlayColor: "rgb(84, 78, 72)",
  },
  {
    id: "11",
    src: "/gallery/03_Concordia_Admiralty_Estates_03.webp",
    width: 1440,
    height: 1920,
    no: "11",
    title: "Lake House",
    meta: "Uppsala, 2022",
    col: 3,
    row: 1,
    mobileCol: 2,
    mobileRow: 2,
    overlayColor: "rgb(56, 54, 47)",
  },
  {
    id: "12",
    src: "/gallery/04_Perkins&Eastman_Genet_City_01.webp",
    width: 1920,
    height: 1280,
    no: "12",
    title: "Boat Jetty",
    meta: "Archipelago, 2021",
    col: 3,
    row: 1,
    mobileCol: 1,
    mobileRow: 1,
    overlayColor: "rgb(53, 45, 43)",
  },
  {
    id: "13",
    src: "/gallery/04_Perkins&Eastman_Genet_City_02.webp",
    width: 1920,
    height: 1280,
    no: "13",
    title: "Reef Pavilion",
    meta: "Coastal Site, 2024",
    col: 3,
    row: 1,
    mobileCol: 1,
    mobileRow: 1,
    overlayColor: "rgb(23, 43, 64)",
  },
  {
    id: "14",
    src: "/gallery/05_RBTA_Brigade_Sevilla_01.webp",
    width: 1440,
    height: 1920,
    no: "14",
    title: "Pine Residence",
    meta: "Värmland, 2022",
    col: 3,
    row: 2,
    mobileCol: 1,
    mobileRow: 2,
    overlayColor: "rgb(74, 53, 47)",
  },
  {
    id: "15",
    src: "/gallery/05_RBTA_Brigade_Sevilla_02.webp",
    width: 1440,
    height: 1920,
    no: "15",
    title: "Reflection House",
    meta: "Lake Site, 2020",
    col: 6,
    row: 1,
    mobileCol: 2,
    mobileRow: 1,
    overlayColor: "rgb(60, 61, 42)",
  },
  {
    id: "16",
    src: "/gallery/05_RBTA_Brigade_Sevilla_03.webp",
    width: 1440,
    height: 1920,
    no: "16",
    title: "Covered Porch",
    meta: "Dalarna, 2023",
    col: 3,
    row: 2,
    mobileCol: 1,
    mobileRow: 2,
    overlayColor: "rgb(59, 70, 82)",
  },
  {
    id: "17",
    src: "/gallery/06_Disha_Harmony_01.webp",
    width: 1920,
    height: 1865,
    no: "17",
    title: "Oak House",
    meta: "Bangalore, 2024",
    col: 3,
    row: 1,
    mobileCol: 1,
    mobileRow: 1,
    overlayColor: "rgb(71, 72, 58)",
  },
  {
    id: "18",
    src: "/gallery/06_Disha_Harmony_02.webp",
    width: 1920,
    height: 1920,
    no: "18",
    title: "Linear Residence",
    meta: "Chennai, 2023",
    col: 3,
    row: 2,
    mobileCol: 1,
    mobileRow: 2,
    overlayColor: "rgb(76, 75, 63)",
  },
  {
    id: "19",
    src: "/gallery/06_Disha_Harmony_03.webp",
    width: 1920,
    height: 1920,
    no: "19",
    title: "Cedar Villa",
    meta: "Goa, 2024",
    col: 6,
    row: 1,
    mobileCol: 2,
    mobileRow: 1,
    overlayColor: "rgb(60, 63, 51)",
  },
  {
    id: "20",
    src: "/gallery/06_Disha_Harmony_04.webp",
    width: 1920,
    height: 1920,
    no: "20",
    title: "Atrium House",
    meta: "Hyderabad, 2022",
    col: 3,
    row: 1,
    mobileCol: 1,
    mobileRow: 1,
    overlayColor: "rgb(62, 61, 53)",
  },
  {
    id: "21",
    src: "/gallery/07_Asssetz_The_Secret_Lake_01.webp",
    width: 1920,
    height: 1280,
    no: "21",
    title: "Terrace Residence",
    meta: "Mumbai, 2023",
    col: 3,
    row: 1,
    mobileCol: 1,
    mobileRow: 2,
    overlayColor: "rgb(53, 57, 48)",
  },
  {
    id: "22",
    src: "/gallery/07_Asssetz_The_Secret_Lake_03.webp",
    width: 1920,
    height: 1280,
    no: "22",
    title: "Courtyard Villa",
    meta: "Kochi, 2024",
    col: 4,
    row: 2,
    mobileCol: 2,
    mobileRow: 2,
    overlayColor: "rgb(94, 74, 47)",
  },
  {
    id: "23",
    src: "/gallery/07_Asssetz_The_Secret_Lake_02.webp",
    width: 1920,
    height: 1920,
    no: "23",
    title: "Concrete Pavilion",
    meta: "Pondicherry, 2022",
    col: 2,
    row: 1,
    mobileCol: 1,
    mobileRow: 1,
    overlayColor: "rgb(56, 55, 42)",
  },
  {
    id: "24",
    src: "/gallery/08_PSP_Resort.webp",
    width: 1920,
    height: 1920,
    no: "24",
    title: "Sunken Garden",
    meta: "Bangalore, 2023",
    col: 2,
    row: 1,
    mobileCol: 1,
    mobileRow: 1,
    overlayColor: "rgb(72, 83, 82)",
  },
  {
    id: "25",
    src: "/gallery/09_Rain Studio_GCE.webp",
    width: 1920,
    height: 1920,
    no: "25",
    title: "Monsoon House",
    meta: "Kerala, 2024",
    col: 6,
    row: 2,
    mobileCol: 2,
    mobileRow: 2,
    overlayColor: "rgb(77, 72, 55)",
  },
  {
    id: "26",
    src: "/gallery/10_ISKCON_Hyderabad_01.webp",
    width: 1920,
    height: 1920,
    no: "26",
    title: "Quiet Courtyard",
    meta: "Chennai, 2021",
    col: 3,
    row: 1,
    mobileCol: 1,
    mobileRow: 1,
    overlayColor: "rgb(86, 73, 56)",
  },
  {
    id: "27",
    src: "/gallery/10_ISKCON_Hyderabad_02.webp",
    width: 1920,
    height: 1206,
    no: "27",
    title: "Terracotta House",
    meta: "Jaipur, 2023",
    col: 3,
    row: 2,
    mobileCol: 1,
    mobileRow: 2,
    overlayColor: "rgb(74, 72, 57)",
  },
  {
    id: "28",
    src: "/gallery/11_Asssetz_Canvas&Cove_01.webp",
    width: 1920,
    height: 1920,
    no: "28",
    title: "Limestone Villa",
    meta: "Goa, 2022",
    col: 3,
    row: 1,
    mobileCol: 2,
    mobileRow: 1,
    overlayColor: "rgb(52, 53, 49)",
  },
  {
    id: "29",
    src: "/gallery/11_Asssetz_Canvas&Cove_02.webp",
    width: 1920,
    height: 1618,
    no: "29",
    title: "Shadow Pavilion",
    meta: "Delhi, 2024",
    col: 3,
    row: 1,
    mobileCol: 1,
    mobileRow: 1,
    overlayColor: "rgb(56, 48, 36)",
  },
  {
    id: "30",
    src: "/gallery/11_Asssetz_Canvas&Cove_03.webp",
    width: 1919,
    height: 1920,
    no: "30",
    title: "Courtyard Studio",
    meta: "Pune, 2024",
    col: 6,
    row: 1,
    mobileCol: 2,
    mobileRow: 1,
    overlayColor: "rgb(58, 56, 54)",
  },
  {
    id: "31",
    src: "/gallery/11_Asssetz_Canvas&Cove_04.webp",
    width: 1920,
    height: 1920,
    no: "31",
    title: "Riverside House",
    meta: "Rishikesh, 2022",
    col: 3,
    row: 2,
    mobileCol: 1,
    mobileRow: 2,
    overlayColor: "rgb(75, 75, 74)",
  },
  {
    id: "32",
    src: "/gallery/12_ANA_Zion_01.webp",
    width: 1920,
    height: 1919,
    no: "32",
    title: "Open Frame House",
    meta: "Bangalore, 2024",
    col: 3,
    row: 1,
    mobileCol: 1,
    mobileRow: 1,
    overlayColor: "rgb(56, 44, 33)",
  },  {
    id: "35",
    src: "/gallery/13_Srivari_Ekaya_03.webp",
    width: 1920,
    height: 1080,
    no: "35",
    title: "Granite Residence",
    meta: "Coimbatore, 2022",
    col: 2,
    row: 1,
    mobileCol: 1,
    mobileRow: 1,
    overlayColor: "rgb(69, 76, 65)",
  },
  {
    id: "33",
    src: "/gallery/13_Srivari_Ekaya_01.webp",
    width: 1920,
    height: 1920,
    no: "33",
    title: "Tropical Retreat",
    meta: "Goa, 2023",
    col: 4,
    row: 2,
    mobileCol: 2,
    mobileRow: 2,
    overlayColor: "rgb(51, 73, 85)",
  },
  {
    id: "34",
    src: "/gallery/13_Srivari_Ekaya_02.webp",
    width: 1920,
    height: 1662,
    no: "34",
    title: "Glass Pavilion",
    meta: "Mumbai, 2024",
    col: 2,
    row: 1,
    mobileCol: 1,
    mobileRow: 1,
    overlayColor: "rgb(80, 73, 61)",
  },
  {
    id: "36",
    src: "/gallery/14_Hadi_Tehrani_Pune Office.webp",
    width: 1920,
    height: 1280,
    no: "36",
    title: "Forest Courtyard",
    meta: "Munnar, 2023",
    col: 3,
    row: 2,
    mobileCol: 1,
    mobileRow: 2,
    overlayColor: "rgb(90, 86, 75)",
  },
  {
    id: "37",
    src: "/gallery/15_MOAD_Sanctuary_01.webp",
    width: 1920,
    height: 1920,
    no: "37",
    title: "Stone Courtyard",
    meta: "Ooty, 2021",
    col: 3,
    row: 1,
    mobileCol: 1,
    mobileRow: 1,
    overlayColor: "rgb(58, 59, 53)",
  },
  {
    id: "38",
    src: "/gallery/15_MOAD_Sanctuary_02.webp",
    width: 1920,
    height: 1920,
    no: "38",
    title: "Skyline Residence",
    meta: "Mumbai, 2023",
    col: 6,
    row: 1,
    mobileCol: 2,
    mobileRow: 1,
    overlayColor: "rgb(55, 62, 58)",
  },
  {
    id: "39",
    src: "/gallery/16_Avani_House.webp",
    width: 1920,
    height: 1080,
    no: "39",
    title: "Palm House",
    meta: "Goa, 2022",
    col: 3,
    row: 1,
    mobileCol: 1,
    mobileRow: 2,
    overlayColor: "rgb(78, 83, 81)",
  },
  {
    id: "40",
    src: "/gallery/17_Amara_Ahana_01.webp",
    width: 1920,
    height: 1920,
    no: "40",
    title: "Minimalist Villa",
    meta: "Bangalore, 2024",
    col: 3,
    row: 2,
    mobileCol: 1,
    mobileRow: 2,
    overlayColor: "rgb(65, 60, 48)",
  },
  {
    id: "41",
    src: "/gallery/17_Amara_Ahana_02.webp",
    width: 1920,
    height: 1920,
    no: "41",
    title: "Lightwell House",
    meta: "Chennai, 2023",
    col: 4,
    row: 2,
    mobileCol: 2,
    mobileRow: 2,
    overlayColor: "rgb(80, 72, 60)",
  },
  {
    id: "42",
    src: "/gallery/18_Hadi_Tehrani_Pune Office_01.webp",
    width: 1920,
    height: 1920,
    no: "42",
    title: "Red Earth Residence",
    meta: "Pune, 2022",
    col: 2,
    row: 1,
    mobileCol: 1,
    mobileRow: 1,
    overlayColor: "rgb(88, 90, 87)",
  },
  {
    id: "43",
    src: "/gallery/18_Hadi_Tehrani_Pune Office_02.webp",
    width: 1920,
    height: 1920,
    no: "43",
    title: "Canopy House",
    meta: "Kerala, 2024",
    col: 2,
    row: 1,
    mobileCol: 1,
    mobileRow: 1,
    overlayColor: "rgb(69, 72, 54)",
  },
  {
    id: "44",
    src: "/gallery/19_Arun Nalapat&Karl_Princic_Valley_01.webp",
    width: 1920,
    height: 1439,
    no: "44",
    title: "Horizon Pavilion",
    meta: "Alibaug, 2023",
    col: 6,
    row: 2,
    mobileCol: 2,
    mobileRow: 2,
    overlayColor: "rgb(51, 55, 61)",
  },
  {
    id: "45",
    src: "/gallery/19_Arun Nalapat&Karl_Princic_Valley_02.webp",
    width: 1920,
    height: 822,
    no: "45",
    title: "Courtyard Loft",
    meta: "Hyderabad, 2024",
    col: 3,
    row: 1,
    mobileCol: 1,
    mobileRow: 1,
    overlayColor: "rgb(80, 73, 61)",
  },
  {
    id: "46",
    src: "/gallery/19_Arun Nalapat&Karl_Princic_Valley_03.webp",
    width: 1920,
    height: 1274,
    no: "46",
    title: "Walled Garden",
    meta: "Kochi, 2023",
    col: 3,
    row: 2,
    mobileCol: 1,
    mobileRow: 2,
    overlayColor: "rgb(67, 47, 57)",
  },
  {
    id: "47",
    src: "/gallery/20_MOAD_Cove_01.webp",
    width: 1920,
    height: 1080,
    no: "47",
    title: "Walled Garden",
    meta: "Kochi, 2023",
    col: 3,
    row: 2,
    mobileCol: 1,
    mobileRow: 2,
    overlayColor: "rgb(67, 47, 57)",
  },
  {
    id: "48",
    src: "/gallery/20_MOAD_Cove_02.webp",
    width: 1920,
    height: 1920,
    no: "48",
    title: "Walled Garden",
    meta: "Kochi, 2023",
    col: 3,
    row: 2,
    mobileCol: 1,
    mobileRow: 2,
    overlayColor: "rgb(67, 47, 57)",
  },
  {
    id: "49",
    src: "/gallery/21_MYVN_Jeyalakshmi_01.webp",
    width: 1920,
    height: 1440,
    no: "49",
    title: "Walled Garden",
    meta: "Kochi, 2023",
    col: 3,
    row: 2,
    mobileCol: 1,
    mobileRow: 2,
    overlayColor: "rgb(67, 47, 57)",
  },
  {
    id: "50",
    src: "/gallery/21_MYVN_Jeyalakshmi_02.webp",
    width: 1920,
    height: 1440,
    no: "50",
    title: "Walled Garden",
    meta: "Kochi, 2023",
    col: 3,
    row: 2,
    mobileCol: 1,
    mobileRow: 2,
    overlayColor: "rgb(67, 47, 57)",
  },
  {
    id: "51",
    src: "/gallery/22_RED_The_Arc.webp",
    width: 1920,
    height: 1080,
    no: "51",
    title: "Walled Garden",
    meta: "Kochi, 2023",
    col: 3,
    row: 2,
    mobileCol: 1,
    mobileRow: 2,
    overlayColor: "rgb(67, 47, 57)",
  },
  {
    id: "52",
    src: "/gallery/23_Amara_Sesha.webp",
    width: 1920,
    height: 1920,
    no: "52",
    title: "Walled Garden",
    meta: "Kochi, 2023",
    col: 3,
    row: 2,
    mobileCol: 1,
    mobileRow: 2,
    overlayColor: "rgb(67, 47, 57)",
  },
  {
    id: "53",
    src: "/gallery/24_Midori Architects_Notion_Of_Steel_Winner.webp",
    width: 1920,
    height: 1920,
    no: "53",
    title: "Walled Garden",
    meta: "Kochi, 2023",
    col: 3,
    row: 2,
    mobileCol: 1,
    mobileRow: 2,
    overlayColor: "rgb(67, 47, 57)",
  },
];

export type GalleryRow = {
  rowType: string;
  items: GalleryItem[];
};

export const galleryRows: GalleryRow[] = [
  {
    rowType: "duo",
    items: [galleryItems[0], galleryItems[1]],
  },
  {
    rowType: "quad",
    items: [galleryItems[2], galleryItems[3], galleryItems[4], galleryItems[5]],
  },
  {
    rowType: "duo",
    items: [galleryItems[6], galleryItems[7]],
  },
  {
    rowType: "feature-left",
    items: [galleryItems[8], galleryItems[9], galleryItems[10]],
  },
  {
    rowType: "duo",
    items: [galleryItems[11], galleryItems[12]],
  },
  {
    rowType: "trio",
    items: [galleryItems[13], galleryItems[14], galleryItems[15]],
  },
  {
    rowType: "quad",
    items: [
      galleryItems[16],
      galleryItems[17],
      galleryItems[18],
      galleryItems[19],
    ],
  },
  {
    rowType: "feature-left",
    items: [galleryItems[20], galleryItems[21], galleryItems[22]],
  },
  {
    rowType: "duo",
    items: [galleryItems[23], galleryItems[24]],
  },
  {
    rowType: "duo",
    items: [galleryItems[25], galleryItems[26]],
  },

  {
    rowType: "quad",
    items: [
      galleryItems[27],
      galleryItems[28],
      galleryItems[29],
      galleryItems[30],
    ],
  },

  {
    rowType: "hero",
    items: [galleryItems[31]],
  },
  {
    rowType: "feature-right",
    items: [galleryItems[32], galleryItems[33], galleryItems[34]],
  },
  {
    rowType: "hero",
    items: [galleryItems[35]],
  },

    {
    rowType: "duo",
    items: [galleryItems[36], galleryItems[37]],
  },
  {
    rowType: "hero",
    items: [galleryItems[38]],
  },
  {
    rowType: "quad",
    items: [
      galleryItems[39],
      galleryItems[40],
      galleryItems[41],
      galleryItems[42],
    ],
  },

  {
    rowType: "duo",
    items: [galleryItems[43], galleryItems[44]],
  },

  {
    rowType: "hero",
    items: [galleryItems[45]],
  },
  {
    rowType: "duo",
    items: [galleryItems[46], galleryItems[47]],
  },
  {
    rowType: "hero",
    items: [galleryItems[48]],
  },
  {
    rowType: "quad",
    items: [
      galleryItems[49],
      galleryItems[50],
      galleryItems[51],
      galleryItems[52],
    ],
  },
];
